# Generated by Django 5.1.6 on 2025-06-13 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="slot",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment",
                to="appointmentapi.appointmentslot",
            ),
        ),
    ]
